// MIT License
//
// Copyright (c) 2026 Otávio Cordeiro
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation

public extension URL {

    /// Creates a preview URL by appending `.preview.jpg` to the filename without its extension.
    ///
    /// This property generates a preview version of an image URL. All preview images
    /// generated by the backend are JPEG format, regardless of the original image format.
    /// The preview URL is constructed by taking the filename (without extension), appending
    /// `.preview`, and then adding the `.jpg` extension.
    ///
    /// - Returns: A new URL with `.preview.jpg` replacing the original file extension
    /// - Example: `https://cdn.some.pics/user/image.png` → `https://cdn.some.pics/user/image.preview.jpg`
    var imagePreviewURL: URL {
        let pathExtension = pathExtension
        let lastPathComponent = lastPathComponent
        let baseURL = deletingLastPathComponent()

        let filenameWithoutExtension = String(
            lastPathComponent.dropLast(pathExtension.count + (pathExtension.isEmpty ? 0 : 1))
        )

        let newFilename = "\(filenameWithoutExtension).preview.jpg"

        return baseURL.appendingPathComponent(newFilename)
    }
}
