import Foundation

public extension URL {

    /// Creates a preview URL by appending `.preview.jpg` to the filename without its extension.
    ///
    /// This property generates a preview version of an image URL. All preview images
    /// generated by the backend are JPEG format, regardless of the original image format.
    /// The preview URL is constructed by taking the filename (without extension), appending
    /// `.preview`, and then adding the `.jpg` extension.
    ///
    /// - Returns: A new URL with `.preview.jpg` replacing the original file extension
    /// - Example: `https://cdn.some.pics/user/image.png` → `https://cdn.some.pics/user/image.preview.jpg`
    var imagePreviewURL: URL {
        let pathExtension = pathExtension
        let lastPathComponent = lastPathComponent
        let baseURL = deletingLastPathComponent()

        let filenameWithoutExtension = String(
            lastPathComponent.dropLast(pathExtension.count + (pathExtension.isEmpty ? 0 : 1))
        )

        let newFilename = "\(filenameWithoutExtension).preview.jpg"

        return baseURL.appendingPathComponent(newFilename)
    }
}
