import Foundation

/// A response model representing a picture from the OMG.LOL pictures API.
///
/// `PictureResponse` encapsulates all the metadata and information about a picture
/// uploaded to the OMG.LOL platform. This model provides a clean, domain-specific
/// representation of picture data that is decoupled from the raw network response format.
///
/// Each picture has both direct access URLs and integration with the "some.pics"
/// service for enhanced picture sharing and discovery capabilities.
public struct PictureResponse: Identifiable, Equatable, Sendable {

    /// The unique identifier for the picture.
    ///
    /// This ID is generated by the OMG.LOL platform when a picture is uploaded
    /// and serves as a permanent, unique reference to the picture across all
    /// API endpoints and sharing services.
    public let id: String

    /// The OMG.LOL address (username) of the user who uploaded the picture.
    ///
    /// This identifies the owner of the picture and is used to construct
    /// the picture's URL path and determine access permissions for
    /// modification operations.
    public let address: String

    /// The timestamp when the picture was uploaded, as seconds since Unix epoch.
    ///
    /// This value represents the creation time of the picture on the OMG.LOL
    /// platform and can be converted to a `Date` object for display purposes.
    /// The timestamp is stored as a `Double` to preserve fractional seconds
    /// from the API response.
    public let created: Double

    /// The MIME type of the picture file.
    ///
    /// This indicates the format of the uploaded image (e.g., "image/jpeg",
    /// "image/png", "image/gif") and can be used by clients to determine
    /// appropriate handling, display, or processing of the image data.
    public let mime: String

    /// The file size of the picture in bytes.
    ///
    /// This represents the total file size of the uploaded picture and can
    /// be used for display purposes, bandwidth considerations, or storage
    /// management. The size is stored as a `Double` to handle large files.
    public let size: Double

    /// The direct URL to access the picture file.
    ///
    /// This URL provides direct access to the picture file hosted on the
    /// user's OMG.LOL address.
    public let url: String

    /// The some.pics URL for enhanced picture sharing and discovery.
    ///
    /// This URL integrates with the "some.pics" service, which provides
    /// additional features for picture sharing, discovery, and social
    /// interaction around visual content from the OMG.LOL community.
    public let somePicsURL: String

    /// An optional description or caption for the picture.
    ///
    /// This user-provided text describes the content or context of the picture
    /// and can be used for display purposes, accessibility, or content discovery.
    /// The description is optional and may be `nil` if not provided by the user.
    public let description: String?

    /// An optional alternative text description for accessibility purposes.
    ///
    /// This text provides an accessible description of the picture's visual
    /// content for users who cannot see the image. It supports screen readers
    /// and other assistive technologies. The alt text is optional and may be
    /// `nil` if not provided by the user.
    public let alt: String?

    /// An array of tags associated with the picture for categorization and discovery.
    ///
    /// These user-defined tags enable content organization, filtering, and search
    /// functionality. Tags can be used to group related pictures or identify
    /// specific themes, events, or characteristics of the visual content. The
    /// array may be empty if no tags have been assigned to the picture.
    public let tags: [String]

    // MARK: - Lifecycle

    public init(
        id: String,
        address: String,
        created: Double,
        mime: String,
        size: Double,
        url: String,
        somePicsURL: String,
        description: String? = nil,
        alt: String? = nil,
        tags: [String]
    ) {
        self.id = id
        self.address = address
        self.created = created
        self.mime = mime
        self.size = size
        self.url = url
        self.somePicsURL = somePicsURL
        self.description = description
        self.alt = alt
        self.tags = tags
    }
}
