import Foundation
import SwiftData

/// A SwiftData model representing a picture stored in the local database.
///
/// This model is the persistent representation of pictures in the app's local storage.
/// It's designed to maintain a complete collection of user's pictures for offline access
/// and management. Each picture represents an uploaded image with its metadata,
/// URLs, and optional descriptive content.
///
/// The model uses SwiftData's `@Model` macro for automatic persistence capabilities and
/// includes unique constraints on the picture ID to prevent duplicate pictures.
/// All properties are publicly readable but privately settable to maintain data integrity.
///
/// Pictures have both direct access URLs and integration with the "some.pics"
/// service for enhanced picture sharing and discovery capabilities.
///
/// Usage example:
/// ```swift
/// let descriptor = FetchDescriptor<SomePicture>.makeDefault()
/// let pictures = try modelContext.fetch(descriptor)
/// ```
@Model
public final class SomePicture {

    // MARK: - Properties

    /// The unique identifier for the picture.
    ///
    /// This ID is generated by the OMG.LOL platform when a picture is uploaded
    /// and serves as a permanent, unique reference to the picture across all
    /// API endpoints and sharing services. It's used as the unique constraint
    /// key to prevent duplicate pictures in local storage.
    public private(set) var id: String

    /// The OMG.LOL address (username) of the user who uploaded the picture.
    ///
    /// This identifies the owner of the picture and is used to construct
    /// the picture's URL path and determine access permissions for
    /// modification operations. It enables multi-user picture management
    /// within the same app instance.
    public private(set) var address: String

    /// The timestamp when the picture was uploaded, as seconds since Unix epoch.
    ///
    /// This value represents the creation time of the picture on the OMG.LOL
    /// platform and can be converted to a `Date` object for display purposes.
    /// The timestamp is stored as a `Double` to preserve fractional seconds
    /// from the API response and is used for chronological sorting.
    public private(set) var created: Double

    /// The MIME type of the picture file.
    ///
    /// This indicates the format of the uploaded image (e.g., "image/jpeg",
    /// "image/png", "image/gif") and can be used by clients to determine
    /// appropriate handling, display, or processing of the image data.
    public private(set) var mime: String

    /// The file size of the picture in bytes.
    ///
    /// This represents the total file size of the uploaded picture and can
    /// be used for display purposes, bandwidth considerations, or storage
    /// management. The size is stored as a `Double` to handle large files
    /// accurately.
    public private(set) var size: Double

    /// The direct URL to access the picture file.
    ///
    /// This URL provides direct access to the picture file hosted on the
    /// user's OMG.LOL address and can be used for loading, displaying,
    /// or sharing the image content.
    public private(set) var url: String

    /// The some.pics URL for enhanced picture sharing and discovery.
    ///
    /// This URL integrates with the "some.pics" service, which provides
    /// additional features for picture sharing, discovery, and social
    /// interaction around visual content from the OMG.LOL community.
    public private(set) var somePicsURL: String

    /// An optional description or caption for the picture.
    ///
    /// This user-provided text describes the content or context of the picture
    /// and can be used for display purposes, accessibility, or content discovery.
    /// The caption is optional and may be `nil` if not provided by the user.
    /// Note: This maps to the `description` field from `StorablePicture`.
    public private(set) var caption: String?

    /// An optional alternative text description for accessibility purposes.
    ///
    /// This text provides an accessible description of the picture's visual
    /// content for users who cannot see the image. It supports screen readers
    /// and other assistive technologies. The alt text is optional and may be
    /// `nil` if not provided by the user.
    public private(set) var alt: String?

    /// An array of tags associated with the picture for categorization and discovery.
    ///
    /// These user-defined tags enable content organization, filtering, and search
    /// functionality. Tags can be used to group related pictures or identify
    /// specific themes, events, or characteristics of the visual content. The
    /// array may be empty if no tags have been assigned to the picture.
    public private(set) var tags: [String]

    // MARK: - Unique constraints

    /// Ensures each picture has a unique ID in the database.
    ///
    /// This constraint prevents duplicate pictures from being stored and ensures
    /// that each picture ID is unique across all users. The picture ID serves as
    /// the primary unique identifier for pictures in local storage.
    #Unique<SomePicture>([\.id])

    // MARK: - Lifecycle

    /// Initializes a new picture with all required data and metadata.
    ///
    /// This initializer is typically used by the persistence service when
    /// converting from `StorablePicture` objects during data synchronization
    /// via the `makePicture` factory method.
    ///
    /// - Parameters:
    ///   - id: The unique identifier for the picture.
    ///   - address: The OMG.LOL address of the user who uploaded the picture.
    ///   - created: The upload timestamp as seconds since Unix epoch.
    ///   - mime: The MIME type of the picture file.
    ///   - size: The file size of the picture in bytes.
    ///   - url: The direct URL to access the picture file.
    ///   - somePicsURL: The some.pics URL for enhanced sharing and discovery.
    ///   - caption: An optional description or caption for the picture.
    ///   - alt: An optional alternative text description for accessibility.
    public init(
        id: String,
        address: String,
        created: Double,
        mime: String,
        size: Double,
        url: String,
        somePicsURL: String,
        caption: String? = nil,
        alt: String? = nil,
        tags: [String]
    ) {
        self.id = id
        self.address = address
        self.created = created
        self.mime = mime
        self.size = size
        self.url = url
        self.somePicsURL = somePicsURL
        self.caption = caption
        self.alt = alt
        self.tags = tags
    }
}
